Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./src
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /
